### ISSUE TITLE
_(:з」∠)_

### ISSUE THREAD

**Issue by sunshihao** [panzekun/vue-app#6]
我点了半天小黄人，发现其并不能登录~~

**Comment by panzekun** [comment]
呃，非常抱歉，小黄人没人做登陆的逻辑 ，只是放着个界面而已，可以直接输入/home路由跳转首页




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Sunny"<notifications@github.com&gt;; 
发送时间: 2020年10月28日(星期三) 中午11:07
收件人: "panzekun/vue-app"<vue-app@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [panzekun/vue-app] _(:з」∠)_ (#6)





 
我点了半天小黄人，发现其并不能登录~~
